---
# tasks file for nginx

- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest
    update_cache: yes 
    force_apt_get: yes

- name: Install required system packages
  apt:
   name: "{{ item }}"
   state: latest 
   update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
   repo: deb https://download.docker.com/linux/ubuntu xenial stable
   state: present

- name: Update apt and install docker-ce
  apt: 
   update_cache: yes 
   name: docker-ce 
   state: latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

- name: Set up nginx directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - sites-available
    - sites-enabled

- name: Add Nginx config file
  template:
    src:  nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0755
    owner: root
    group: root

- name: Add Nginx reverse-config file
  template:
    src: reverse_proxy.conf.j2
    dest: /etc/nginx/sites-available/reverse_proxy.conf
    mode: 0755
    owner: root
    group: root

- name: Install Nginx
  docker_container:
    name: nginx
    image: nginx
    detach: true
    tty: true
    ports:
      - 8080:80
    volumes:
        - /etc/nginx/:/etc/nginx/
        - /etc/nginx/sites-enabled/:/etc/nginx/sites-available/