---

- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest
    update_cache: yes 
    force_apt_get: yes

- name: Install required system packages
  apt:
   name: "{{ item }}"
   state: latest 
   update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
   repo: deb https://download.docker.com/linux/ubuntu xenial stable
   state: present

- name: Update apt and install docker-ce
  apt: 
   update_cache: yes 
   name: docker-ce 
   state: latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull default Docker image
  docker_image:
    name: docker
    source: pull


- name: Start node_exporter container
  become: yes
  docker_container:
    name: "{{ prometheus_node_exporter_container_name }}"
    hostname: "{{ prometheus_node_exporter_container_name }}"
    image: "{{ prometheus_node_exporter_image }}"
    published_ports:
      - 9100:9100
    restart_policy: always
