---

- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest
    update_cache: yes 
    force_apt_get: yes

- name: Install required system packages
  apt:
   name: "{{ item }}"
   state: latest 
   update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
   repo: deb https://download.docker.com/linux/ubuntu xenial stable
   state: present

- name: Update apt and install docker-ce
  apt: 
   update_cache: yes 
   name: docker-ce 
   state: latest

#- name: Install Docker Module for Python
  #pip:
  #  name: docker

- name: Pull default Docker image
  docker_image:
    name: docker
    source: pull
#- name: "state docker app"
#  become: yes 
#  shell: apt install -y pip3
   


- name: "state docker app"
  become: yes
  shell: apt install python-docker -y

- name: ansible create directory with mode setting example
  file:
    path: /etc/redis
    state: directory
    mode: "u=rw,g=wx,o=rwx"

- include_tasks: install_redis_master.yml
  tags:
    - "Redis-Cluster"

- include_tasks: install_redis_slave.yml
  tags:
    - "Redis-Cluster"

#- include_tasks: install_redis_sentinel.yml
#  tags:
#    - "Redis-Cluster"

