 - name: data container
   docker_container:
     name: redis-data
     image: redis
     state: present
     volumes:
      - /data
     command: "true"
   when: use_backup_container
 
 - name: redis container
   docker_container:
     name: redis
     image: redis
     command: ["redis-server", "--requirepass {{ redis_password }}"]
     state: started
     expose:
      - "6380"
     ports: 
       - "6380:6379"
     volumes_from:
       - redis-data