---
- hosts: all
  gather_facts: no
  vars:  
    ansible_user: ubuntu 
    ansible_ssh_private_key_file: /Users/oawoga/play/redis_blue_green/ansible/inventory/test20.pem
  
- name: apply redis configuration 
  hosts: map_blue_Server
  vars:
    - ansible_host: "{{ public_ip_address }}"
    - ansible_user: ubuntu
  become: yes
  roles:
    - redis
    
- name: apply app configuration 
  hosts:  map_blue_Server
  become: yes
  vars:  
    - ansible_host: "{{ public_ip_address }}"
    - ansible_user: ubuntu
  roles:
    - app
  
- name: Build prometheus and grafana dashboard configuration 
  hosts: map_blue_Server
  vars:
    - ansible_host: "{{ public_ip_address }}"
    - ansible_user: ubuntu
  roles:
    - grafana
   