---
- hosts: all
  gather_facts: no
  become: true
  vars:
    ansible_user: ubuntu 
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /Users/oawoga/play/redis_blue_green_update/terraform/olukey

- name: apply nginx configuration 
  hosts: nginx_Server
  vars:
    ansible_host: "{{ public_ip_address }}"
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
  become: true
  roles: 
    - nginx

- name: docker setup dashboard configuration 
  become: yes
  hosts: redis_Server
  vars:
    - ansible_host: "{{ public_ip_address }}"
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: /Users/oawoga/play/redis_blue_green_update/terraform/olukey
  roles:
    - docker_setup
    - redis-sentinel
    
- name: install app on blue Server configuration 
  hosts: 
    - blue_Server 
  vars:
    - ansible_host: "{{ public_ip_address }}"
    - ansible_user: ubuntu
  become: yes
  roles:
    - docker_setup
    - app

- name: install app on green Server configuration 
  hosts: 
    - green_Server 
  vars:
    ansible_host: "{{ public_ip_address }}"
    ansible_user: ubuntu
 
  roles:
     - docker_setup
     - app
  
  
- name: apply app configuration 
  hosts:  jenkins_Server
 
  vars:  
    ansible_host: "{{ public_ip_address }}"
    ansible_user: ubuntu
  roles:
   - docker_setup
   - grafana
   
    

   


  